// Capacitor configuration removed - this is an Expo project
// If you need Capacitor functionality, install @capacitor/android and related plugins
// and uncomment the following:
 // include ':capacitor-android'
 // project(':capacitor-android').projectDir = new File('../node_modules/@capacitor/android/capacitor')

 // include ':capacitor-camera'
 // project(':capacitor-camera').projectDir = new File('../node_modules/@capacitor/camera/android')

 // include ':capacitor-filesystem'
 // project(':capacitor-filesystem').projectDir = new File('../node_modules/@capacitor/filesystem/android')
